<?php
$isExternal=(($user['access_type']??'INTERNAL')==='EXTERNAL');
$isSupport=!$isExternal&&(\App\Core\Auth::can('tickets.view_queue')||\App\Core\Auth::can('tickets.change_status')||\App\Core\Auth::can('tickets.view_all'));
$helpContext=$isSupport?'support_center':($isExternal?'my_tickets':'requester_home');
$statusLabels=['NEW'=>'Nuevo','AVAILABLE'=>'Por atender','IN_PROGRESS'=>'En proceso','PENDING'=>'En espera','RESOLVED'=>'Resuelto','CLOSED'=>'Cerrado','REOPENED'=>'Reabierto','CANCELLED'=>'Cancelado'];
$pageTitle='Inicio';$pageSection='Inicio';$activeNav='home';
require APP_ROOT.'/app/Views/shared/app_start.php';
?>
<div class="dashboard-primary-row"><div class="page-heading"><div><h1 class="page-title"><?= $isSupport?'Centro de trabajo':($isExternal?'Mis casos asignados':'Mis solicitudes') ?></h1><p class="page-subtitle"><?= $isSupport?'Tus casos activos y los pendientes por atender.':($isExternal?'Solo verás los casos especiales asignados a tu cuenta.':'Consulta el estado de tus solicitudes o registra una nueva.') ?></p></div></div><?php if($isSupport): ?><a class="btn btn-primary dashboard-primary-button" href="<?= APP_BASE_URL ?>/tickets/queue">Abrir centro de soporte</a><?php elseif(!$isExternal): ?><a class="btn btn-primary dashboard-primary-button" href="<?= APP_BASE_URL ?>/crear-ticket">+ Nueva solicitud</a><?php endif; ?></div>
<?php if(!empty($flash)): ?><div class="alert alert-success"><?= htmlspecialchars($flash['message']) ?></div><?php endif; ?>
<div class="dashboard-overview"><section class="card dashboard-welcome"><h2>Hola, <?= htmlspecialchars($user['full_name']) ?></h2><p><?= $isSupport?'Tu perfil está listo para gestionar soporte.':($isExternal?'Tu acceso está limitado a los casos autorizados.':'Tu cuenta está lista para dar seguimiento a tus solicitudes.') ?></p><div class="hero-meta"><span class="badge badge-primary"><?= htmlspecialchars($user['role_name']) ?></span><?php if($user['status']==='PENDING'): ?><span class="badge badge-warning">Pendiente de asignación</span><?php else: ?><span class="badge badge-success">Acceso activo</span><?php endif; ?></div><?php if(!$isExternal&&!empty($assignment['park_name'])): ?><div class="stat-note" style="margin-top:12px"><?= htmlspecialchars($assignment['park_name']) ?><?= !empty($assignment['area_name'])?' · '.htmlspecialchars($assignment['area_name']):'' ?></div><?php endif; ?></section>
<?php if($isSupport): ?><section class="card stat"><span class="stat-label">Mis casos activos</span><b><?= (int)($supportStats['mine']??0) ?></b><div class="stat-note">Casos que ya estás atendiendo.</div></section><section class="card stat"><span class="stat-label">Por atender</span><b><?= (int)($supportStats['available']??0) ?></b><div class="stat-note">Casos disponibles en la cola.</div></section><?php else: ?><section class="card stat"><span class="stat-label">Abiertas</span><b><?= (int)($ticketStats['open_count']??0) ?></b><div class="stat-note">Solicitudes que aún requieren seguimiento.</div></section><section class="card stat"><span class="stat-label">Total</span><b><?= (int)($ticketStats['total']??0) ?></b><div class="stat-note">Historial asociado a tu acceso.</div></section><?php endif; ?></div>
<?php if(!$isSupport): ?><section class="card dashboard-recent"><div class="dashboard-recent-head"><h2><?= $isExternal?'Casos recientes':'Solicitudes recientes' ?></h2><a href="<?= APP_BASE_URL ?>/mis-tickets">Ver todas</a></div><div class="dashboard-recent-list"><?php foreach(($recentTickets??[]) as $t): ?><a class="dashboard-recent-item" href="<?= APP_BASE_URL ?>/tickets/view?id=<?= (int)$t['id'] ?>"><div><strong><?= htmlspecialchars($t['subject']) ?></strong><span><?= htmlspecialchars($t['ticket_number']) ?> · <?= htmlspecialchars(date('d/m/Y H:i',strtotime($t['created_at']))) ?></span></div><div class="dashboard-recent-status"><?= htmlspecialchars($statusLabels[$t['status']]??$t['status']) ?> →</div></a><?php endforeach; ?><?php if(empty($recentTickets)): ?><div class="empty-state"><?= $isExternal?'No tienes casos asignados por el momento.':'Todavía no tienes solicitudes registradas.' ?></div><?php endif; ?></div></section><?php endif; ?>
<?php require APP_ROOT.'/app/Views/shared/app_end.php'; ?>