<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fails=0;
function b(string $p):string{$v=@file_get_contents($p);return is_string($v)?$v:'';}
function ok2(bool $c,string $m):void{global $fails;echo ($c?'[OK] ':'[FALLO] ').$m.PHP_EOL;if(!$c)$fails++;}
$ticket=b($root.'/app/Controllers/TicketController.php');$admin=b($root.'/app/Controllers/AdminController.php');$show=b($root.'/app/Views/tickets/show.php');$queue=b($root.'/app/Views/tickets/queue.php');$management=b($root.'/app/Controllers/ManagementController.php');$xlsx=b($root.'/app/Controllers/XlsxExportController.php');$search=b($root.'/app/Controllers/SearchController.php');$notifications=b($root.'/app/Services/NotificationService.php');$form=b($root.'/app/Views/tickets/public_create.php');
ok2(str_contains($ticket,"SELECT c.id,c.code,p.code parent_code"),'Alta consulta código y padre de categoría');ok2(str_contains($ticket,'inferInitialClassification'),'Alta usa inferencia automática');ok2(!str_contains($form,'public-itsm-classification'),'Formulario público elimina bloque ITSM');
ok2(str_contains($ticket,'current_requester_name'),'Detalle consulta nombre actual del solicitante');ok2(str_contains($ticket,'current_requester_park_name'),'Detalle consulta ubicación organizacional actual');ok2(str_contains($show,'Dónde ocurrió'),'Detalle distingue ubicación histórica del caso');ok2(str_contains($show,'Ubicación actual:'),'Detalle muestra ubicación actual del solicitante a soporte');
ok2(str_contains($queue,"current_requester_name"),'Cola usa identidad actual cuando existe');ok2(str_contains($management,'COALESCE(req.full_name,t.requester_name) requester_name'),'Gestión usa nombre actual sin reescribir ticket');ok2(str_contains($xlsx,'COALESCE(req.full_name,t.requester_name) requester_name'),'Excel usa identidad actual del solicitante');ok2(str_contains($search,'COALESCE(req.full_name,t.requester_name) requester_name'),'Búsqueda usa identidad actual del solicitante');ok2(str_contains($notifications,'COALESCE(req.email,t.requester_email) requester_email'),'Notificaciones usan correo actual cuando existe usuario vinculado');
ok2(str_contains($admin,"UPDATE tickets SET requester_user_id=? WHERE requester_user_id IS NULL"),'Administración vincula tickets históricos sin identidad');ok2(!str_contains($admin,'UPDATE tickets SET requester_name='),'Administración no reescribe nombre histórico');ok2(!str_contains($admin,'UPDATE tickets SET requester_email='),'Administración no reescribe correo histórico');ok2(!str_contains($admin,'UPDATE tickets SET park_id='),'Administración no reescribe ubicación histórica');ok2(str_contains($management,'LEFT JOIN parks p ON p.id=t.park_id'),'Informes conservan parque histórico del ticket');ok2(str_contains($xlsx,'LEFT JOIN parks p ON p.id=t.park_id'),'Excel conserva parque histórico del ticket');
if($fails){fwrite(STDERR,PHP_EOL."[ERROR] {$fails} validación(es) fallaron.".PHP_EOL);exit(1);}echo PHP_EOL."[OK] Regresión clasificación automática + histórico completada.".PHP_EOL;
