<?php
declare(strict_types=1);
$root=dirname(__DIR__);$router=file_get_contents($root.'/public/index.php');
$cp=$root.'/app/Controllers/AgendaController.php';$controller=is_file($cp)?file_get_contents($cp):'';
$viewPath=$root.'/app/Views/agenda/index.php';$view=is_file($viewPath)?file_get_contents($viewPath):'';
$appStartPath=$root.'/app/Views/shared/app_start.php';$appStart=is_file($appStartPath)?file_get_contents($appStartPath):'';
$appEndPath=$root.'/app/Views/shared/app_end.php';$appEnd=is_file($appEndPath)?file_get_contents($appEndPath):'';
$cssPath=$root.'/public/assets/css/agenda.css';$css=is_file($cssPath)?file_get_contents($cssPath):'';
$jsPath=$root.'/public/assets/js/agenda.js';$js=is_file($jsPath)?file_get_contents($jsPath):'';
$manualPath=$root.'/app/Views/help/manual.php';$manual=is_file($manualPath)?file_get_contents($manualPath):'';
$ciPath=$root.'/.github/workflows/helpdesk-ci.yml';$ci=is_file($ciPath)?file_get_contents($ciPath):'';
$readmePath=$root.'/README.md';$readme=is_file($readmePath)?file_get_contents($readmePath):'';
$changelogPath=$root.'/CHANGELOG.md';$changelog=is_file($changelogPath)?file_get_contents($changelogPath):'';
$roadmapPath=$root.'/docs/superpowers/plans/2026-09-10-helpdesk-functional-maturation-implementation.md';$roadmap=is_file($roadmapPath)?file_get_contents($roadmapPath):'';$errors=0;
function ok(bool $c,string $m):void{global $errors;echo($c?'[OK] ':'[FALLO] ').$m.PHP_EOL;if(!$c)$errors++;}
ok(str_contains($router,'AgendaController'),'Router conoce AgendaController');
ok(str_contains($router,"['GET','/agenda'"),'Existe GET /agenda');
ok($controller!=='','Existe AgendaController');
ok(str_contains($controller,"['ADMIN','SEMIADMIN','TECHNICIAN','MANAGEMENT','SUPERVISOR']"),'Roles permitidos explicitos');
ok(str_contains($controller,'http_response_code(403)'),'No autorizado recibe 403');
ok(str_contains($controller,'AgendaService'),'Controller delega al servicio');
ok(!str_contains($controller,'SELECT '),'Controller no ejecuta SQL');
ok($view!=='','Existe vista Agenda');
ok($css!=='','Existe CSS Agenda');
ok(str_contains($view,'Calendario'),'Selector Calendario');
ok(str_contains($view,'Lista'),'Selector Lista');
ok(str_contains($view,'name="responsible_user_id"'),'Filtro Responsable');
ok(str_contains($view,'name="park_id"'),'Filtro Parque');
ok(str_contains($view,'name="activity_type"'),'Filtro Tipo');
ok(str_contains($view,'name="status"'),'Filtro Estado');
ok(str_contains($view,'name="from"')&&str_contains($view,'name="to"'),'Filtro rango');
ok(str_contains($view,'Pendientes atrasadas'),'Bloque atrasadas');
ok(str_contains($view,'#actividades'),'Enlaces al ticket');
ok(str_contains($view,'agenda-calendar'),'Vista contiene calendario semanal');
ok(str_contains($view,'agenda-calendar-grid'),'Calendario contiene cuadrícula horaria');
ok(str_contains($view,'agenda-calendar-days'),'Calendario contiene siete días');
ok(str_contains($view,'Semana anterior'),'Navegación semana anterior');
ok(str_contains($view,'Hoy'),'Navegación vuelve a hoy');
ok(str_contains($view,'Semana siguiente'),'Navegación semana siguiente');
ok(str_contains($view,'Conflicto de horario'),'Conflicto visible en actividades');
ok(str_contains($css,'@media(max-width:1023px)'),'Responsive para iPad vertical');
ok(str_contains($css,'@media(max-width:760px)'),'Responsive para móvil');
ok($js!=='','Existe JavaScript progresivo de Agenda');
ok(str_contains($js,".agenda-event[data-start-slot][data-span-slots]"),'JavaScript posiciona eventos de calendario');
ok(substr_count($view,'<section class="agenda-calendar"')===1,'Vista renderiza un solo calendario semanal');
ok(substr_count($view,'class="agenda-calendar-grid"')===1,'Vista renderiza una sola cuadrícula de calendario');
ok(substr_count($view,'class="agenda-calendar-days"')===1,'Vista renderiza un solo contenedor responsive de días');
$baseCalendarGrids=preg_match_all('/\.agenda-calendar-grid\{[^}]*grid-template-columns/s',$css);
ok($baseCalendarGrids===1,'CSS conserva una sola definicion estructural de agenda-calendar-grid');
ok(!str_contains($css,'.agenda-hours'),'CSS no conserva implementación anterior de agenda-hours');
ok(!str_contains($css,'.agenda-calendar-day{'),'CSS no conserva implementación anterior de agenda-calendar-day');
// Pulido visual detectado en validación PC TEST: multiday, navegación única, atrasadas y programación compacta.
ok(str_contains($view,'$calendarActivities')&&str_contains($view,'$multiDayActivities'),'Calendario separa actividades horarias de actividades de varios días');
ok(str_contains($view,'agenda-multiday-strip')&&str_contains($view,'agenda-multiday-item'),'Calendario muestra franja compacta para actividades de varios días');
ok(str_contains($view,'multiDayRange'),'Actividad de varios días muestra rango con fecha y hora');
ok(substr_count($view,'>Semana anterior</a>')===1&&substr_count($view,'>Semana siguiente</a>')===1,'Navegación semanal no se duplica');
ok(str_contains($view,'count($overdue)>0')&&str_contains($view,'agenda-overdue-items'),'Atrasadas solo muestran bloque cuando hay filas renderizables');
ok(str_contains($css,'.agenda-program-search{')&&str_contains($css,'grid-template-columns:minmax(0,1fr) auto'),'Programar actividad usa buscador compacto en escritorio');
ok(str_contains($css,'.agenda-multiday-strip{')&&str_contains($css,'.agenda-multiday-item{'),'CSS define presentación de actividades multiday');
ok(str_contains($appStart,"\$canAgenda=!\$isExternal&&in_array((string)Auth::role(),['ADMIN','SEMIADMIN','TECHNICIAN','MANAGEMENT','SUPERVISOR'],true);"),'Shell define elegibilidad explicita de Agenda');
ok(str_contains($appStart,"activeNav==='agenda'"),'Shell marca Agenda como navegacion activa');
ok(str_contains($appStart,"/agenda"),'Shell enlaza Agenda');
ok(str_contains($appStart,'agenda.css')&&str_contains($appStart,"activeNav==='agenda'"),'Shell carga agenda.css solo en Agenda');
ok(str_contains($appEnd,'agenda.js')&&str_contains($appEnd,"activeNav==='agenda'")&&str_contains($appEnd,'defer'),'Shell carga agenda.js diferido solo en Agenda');
ok(str_contains($view,'Programar actividad'),'Vista muestra Programar actividad');
ok(str_contains($view,'name="ticket_q"')&&str_contains($view,'maxlength="100"'),'Programar actividad usa busqueda ticket_q limitada');
ok(str_contains($view,'$ticketMatches')&&str_contains($view,'ticket_url')&&str_contains($view,'#actividades'),'Programar actividad lista coincidencias con enlaces a actividades');
ok(str_contains($view,'hidden" name="program" value="1"'),'Programar actividad preserva modo program');
ok(str_contains($view,'hidden" name="view"')&&str_contains($view,"\$filters['view']??'calendar'"),'Programar actividad preserva vista actual');
ok(strlen($manual)>0&&str_contains($manual,'Agenda')&&str_contains($manual,'Calendario')&&str_contains($manual,'Lista'),'Manual documenta Agenda/Calendario/Lista');
ok(str_contains($readme,'| 6 | Agenda | **Implementada')&&str_contains($readme,'Calendario')&&str_contains($readme,'Lista'),'README documenta estado y vistas de Agenda');
ok(str_contains($changelog,'Agenda')&&str_contains($changelog,'BD: sin cambios'),'CHANGELOG documenta Agenda sin cambios de BD');
ok(str_contains($roadmap,'Fase 6')&&str_contains($roadmap,'IMPLEMENTADA')&&str_contains($roadmap,'Fase 7'),'Roadmap marca Fase 6 implementada y Fase 7 siguiente');
ok(str_contains($ci,'php tests/phase6_agenda_service_regression.php')&&str_contains($ci,'php tests/phase6_agenda_ui_regression.php'),'CI ejecuta regresiones Phase 6 service y UI');
if($errors)exit(1);
