<?php
declare(strict_types=1);
$root=$argv[1]??dirname(__DIR__);$fails=0;
function body(string $p):string{$v=@file_get_contents($p);return is_string($v)?$v:'';}
function ok(bool $c,string $m):void{global $fails;echo ($c?'[OK] ':'[FALLO] ').$m.PHP_EOL;if(!$c)$fails++;}
$notif=body($root.'/public/assets/js/notifications.js');$appStart=body($root.'/app/Views/shared/app_start.php');$tour=body($root.'/public/assets/js/help-tour.js');$manual=body($root.'/app/Views/help/manual.php');$publicHome=body($root.'/app/Views/tickets/public_home.php');$publicCreate=body($root.'/app/Views/tickets/public_create.php');$dashboard=body($root.'/app/Views/dashboard/index.php');
ok(str_contains($appStart,'data-notification-base-url='),'Campanita expone base de la instancia actual');ok(str_contains($appStart,'data-notification-fallback-url='),'Campanita expone destino seguro');ok(str_contains($appStart,'data-notification-ticket-id='),'Notificación conserva ticket_id');ok(str_contains($notif,'INTERNAL_ROUTE_MARKERS'),'Resolvedor cubre rutas internas');ok(str_contains($notif,'notificationTicketFallback'),'Campanita reconstruye ticket');ok(str_contains($notif,"link.getAttribute('href')||''"),'Campanita resuelve href original');ok(str_contains($notif,'protocol!==\'http:\'&&destination.protocol!==\'https:\''),'Campanita rechaza protocolos inseguros');
ok(!str_contains($tour,"['.public-form-head'"),'Tutorial no depende de public-form-head legacy');ok(!str_contains($tour,'[data-public-step="classification"]'),'Tutorial no expone clasificación interna al solicitante');ok(str_contains($tour,"['.public-request-heading'"),'Tutorial usa encabezado actual');ok(str_contains($tour,"'#requester_topic'"),'Tutorial explica selector humano');ok(str_contains($tour,'function resolveTour()'),'Tutorial audita pasos');ok(str_contains($tour,'Recorrido adaptado'),'Tutorial avisa pasos faltantes');ok(str_contains($tour,'requester_home:['),'Tutorial cubre solicitante');ok(str_contains($tour,'external_home:['),'Tutorial cubre proveedor');ok(str_contains($tour,'my_tickets:['),'Tutorial cubre Mis solicitudes');ok(str_contains($tour,'public_home:['),'Tutorial cubre portada');ok(str_contains($publicHome,'assets/js/help-tour.js'),'Portada carga tutorial');ok(str_contains($dashboard,"\$isExternal?'external_home':'requester_home'"),'Dashboard usa contexto específico');
ok(str_contains($manual,'Notificaciones y campanita'),'Manual explica campanita');ok(str_contains($manual,'Convertir entre usuario interno y proveedor externo'),'Manual documenta conversión reversible');ok(str_contains($manual,'no asigna tickets, no cambia permisos ni modifica el alcance'),'Manual define Responsable directo');ok(!str_contains($manual,'Caja Chica/NIT, Payout/Kiddies, Tickets Destruidos'),'Manual no congela catálogo viejo');ok(str_contains($manual,'El catálogo se mantiene actualizado'),'Manual remite al catálogo dinámico');ok(str_contains($manual,'Clasificación ITSM'),'Manual mantiene clasificación para soporte');ok(str_contains($publicCreate,'20260912-ITSM21AUTO1'),'Solicitar ayuda fuerza recursos nuevos');
if($fails){fwrite(STDERR,"\n[ERROR] {$fails} validación(es) fallaron.\n");exit(1);}echo "\n[OK] Regresión UX compatible con clasificación automática.\n";
