<?php
use App\Core\Csrf;
$pageTitle='Proveedores externos';$pageSection='Administración';$activeNav='externals';$helpContext='externals';
require APP_ROOT.'/app/Views/shared/app_start.php';
$typeLabels=['PROVIDER'=>'Proveedor','PARTNER'=>'Socio / aliado','OTHER'=>'Otro'];
?>
<link rel="stylesheet" href="<?= htmlspecialchars(APP_PUBLIC_PATH) ?>/assets/css/management.css">
<div class="mgmt-head"><div><span class="mgmt-kicker">Acceso restringido</span><h1>Usuarios externos</h1><p>Proveedores y terceros solo pueden ver los casos especiales que les asignes explícitamente.</p></div></div>
<?php if(!empty($flash)): ?><div class="alert alert-success"><?= htmlspecialchars($flash['message']) ?></div><?php endif; ?>
<section class="external-security"><strong>Regla de seguridad</strong><span>Un usuario externo no accede al Centro de soporte, usuarios, auditoría, métricas ni tickets internos. Su sesión muestra únicamente los casos incluidos en “Acceso externo”.</span></section>
<div class="external-layout">
<section class="mgmt-card"><div class="mgmt-card-head"><div><span>1. Cuenta externa</span><h2>Crear proveedor o tercero</h2></div></div><form method="post" action="<?= APP_BASE_URL ?>/admin/externos/crear" class="external-form" data-single-submit><input type="hidden" name="_csrf" value="<?= Csrf::token() ?>"><label>Proveedor / empresa<input class="form-control" name="organization_name" required placeholder="Nombre de la empresa"></label><label>Tipo<select class="form-control" name="external_type"><option value="PROVIDER">Proveedor</option><option value="PARTNER">Socio / aliado</option><option value="OTHER">Otro</option></select></label><label>Nombre del contacto<input class="form-control" name="name" required placeholder="Nombre completo"></label><label>Correo<input class="form-control" type="email" name="email" required placeholder="correo@proveedor.com"></label><label>Teléfono<input class="form-control" name="phone" placeholder="Opcional"></label><label class="external-full">Notas<input class="form-control" name="notes" placeholder="Servicio, contrato o referencia"></label><div class="external-full"><button class="btn btn-primary">Crear usuario externo</button></div></form></section>
<section class="mgmt-card"><div class="mgmt-card-head"><div><span>2. Caso especial</span><h2>Asignar acceso a un ticket</h2></div></div><form method="post" action="<?= APP_BASE_URL ?>/admin/externos/asignar" class="external-form" data-single-submit><input type="hidden" name="_csrf" value="<?= Csrf::token() ?>"><label class="external-full">Usuario externo<select class="form-control" name="user_id" required><option value="">Selecciona</option><?php foreach($users as $u): ?><option value="<?= (int)$u['id'] ?>"><?= htmlspecialchars(($u['organization_name']?:$u['full_name']).' · '.$u['full_name']) ?></option><?php endforeach; ?></select></label><label class="external-full">Ticket<select class="form-control" name="ticket_id" required><option value="">Selecciona un caso</option><?php foreach($tickets as $t): ?><option value="<?= (int)$t['id'] ?>"><?= htmlspecialchars($t['ticket_number'].' · '.$t['subject'].($t['park_name']?' · '.$t['park_name']:'')) ?></option><?php endforeach; ?></select></label><label class="external-check"><input type="checkbox" name="can_comment" value="1" checked> Puede responder</label><label class="external-check"><input type="checkbox" name="can_upload" value="1" checked> Puede adjuntar archivos</label><div class="external-full"><button class="btn btn-primary">Dar acceso al caso</button></div></form></section>
</div>
<section class="mgmt-card"><div class="mgmt-card-head"><div><span>Cuentas</span><h2>Proveedores registrados</h2></div><b><?= count($users) ?></b></div><div class="external-users"><?php foreach($users as $u): ?><article><div class="external-avatar"><?= htmlspecialchars(mb_strtoupper(mb_substr($u['organization_name']?:$u['full_name'],0,1))) ?></div><div><strong><?= htmlspecialchars($u['organization_name']?:$u['full_name']) ?></strong><span><?= htmlspecialchars($u['full_name']) ?> · <?= htmlspecialchars($u['email']) ?></span><small><?= htmlspecialchars($typeLabels[$u['external_type']]??'Externo') ?> · <?= (int)$u['active_cases'] ?> caso(s) habilitado(s)</small></div></article><?php endforeach; ?><?php if(!$users): ?><div class="empty-state">Todavía no hay usuarios externos.</div><?php endif; ?></div></section>
<section class="mgmt-card"><div class="mgmt-card-head"><div><span>Acceso explícito</span><h2>Casos compartidos actualmente</h2></div></div><div class="table-responsive"><table class="table"><thead><tr><th>Ticket</th><th>Proveedor</th><th>Contacto</th><th>Permisos</th><th>Desde</th><th></th></tr></thead><tbody><?php foreach($access as $x): ?><tr><td><a href="<?= APP_BASE_URL ?>/tickets/view?id=<?= (int)$x['ticket_id'] ?>"><strong><?= htmlspecialchars($x['ticket_number']) ?></strong></a><small><?= htmlspecialchars($x['subject']) ?></small></td><td><?= htmlspecialchars($x['organization_name']??'—') ?></td><td><?= htmlspecialchars($x['full_name']) ?></td><td><?= $x['can_comment']?'Responder · ':'' ?><?= $x['can_upload']?'Adjuntar':'' ?></td><td><?= htmlspecialchars(date('d/m/Y H:i',strtotime($x['granted_at']))) ?></td><td><form method="post" action="<?= APP_BASE_URL ?>/admin/externos/revocar" data-single-submit><input type="hidden" name="_csrf" value="<?= Csrf::token() ?>"><input type="hidden" name="ticket_id" value="<?= (int)$x['ticket_id'] ?>"><input type="hidden" name="user_id" value="<?= (int)$x['user_id'] ?>"><button class="btn btn-outline-secondary btn-sm">Revocar</button></form></td></tr><?php endforeach; ?><?php if(!$access): ?><tr><td colspan="6" class="empty-state">No hay casos compartidos con terceros.</td></tr><?php endif; ?></tbody></table></div></section>
<?php require APP_ROOT.'/app/Views/shared/app_end.php'; ?>