<?php
use App\Core\{Auth,Csrf};
$pageTitle=$problem['problem_number'];$pageSection='Problemas conocidos';$activeNav='problems';$helpContext='problems';
require APP_ROOT.'/app/Views/shared/app_start.php';
?>
<div class="itsm-page problem-workspace">
  <div class="page-heading"><div><span class="ticket-kicker"><?= htmlspecialchars($problem['problem_number']) ?></span><h1 class="page-title"><?= htmlspecialchars($problem['title']) ?></h1><p class="page-subtitle"><?= htmlspecialchars($statuses[$problem['status']]??$problem['status']) ?> · <?= htmlspecialchars($problem['category_name']??'Sin categoría') ?> · <?= htmlspecialchars($problem['park_name']??'General') ?></p></div><div class="topbar-actions"><a class="btn btn-outline-secondary" href="<?= APP_BASE_URL ?>/problems">← Volver</a><?php if(Auth::can('problems.manage')): ?><a class="btn btn-primary" href="<?= APP_BASE_URL ?>/knowledge/new?problem_id=<?= (int)$problem['id'] ?>">Crear artículo desde problema</a><?php endif; ?></div></div>
  <?php if(!empty($flash)): ?><div class="alert alert-success"><?= htmlspecialchars($flash['message']) ?></div><?php endif; ?>
  <div class="problem-summary-grid"><section class="card"><div class="card-body"><span class="ticket-kicker">Resumen</span><h2>Qué ocurre</h2><p class="itsm-longtext"><?= nl2br(htmlspecialchars($problem['description'])) ?></p></div></section><aside class="card"><div class="card-body"><dl class="case-status-list"><div><dt>Estado</dt><dd><?= htmlspecialchars($statuses[$problem['status']]??$problem['status']) ?></dd></div><div><dt>Propietario</dt><dd><?= htmlspecialchars($problem['owner_name']??'Sin propietario') ?></dd></div><div><dt>Ocurrencias</dt><dd><?= (int)$problem['occurrence_count'] ?></dd></div><div><dt>Primera aparición</dt><dd><?= !empty($problem['first_seen_at'])?htmlspecialchars(date('d/m/Y H:i',strtotime($problem['first_seen_at']))):'—' ?></dd></div><div><dt>Última aparición</dt><dd><?= !empty($problem['last_seen_at'])?htmlspecialchars(date('d/m/Y H:i',strtotime($problem['last_seen_at']))):'—' ?></dd></div></dl></div></aside></div>

  <section class="card"><div class="card-body"><div class="itsm-learning-grid"><div><span>Qué encontramos</span><strong>Causa raíz</strong><p><?= nl2br(htmlspecialchars($problem['root_cause']?:'Todavía en investigación.')) ?></p></div><div class="itsm-workaround"><span>Qué hacer temporalmente</span><strong>Workaround</strong><p><?= nl2br(htmlspecialchars($problem['workaround']?:'Aún no se ha documentado un workaround.')) ?></p></div><div><span>Qué corrige definitivamente</span><strong>Solución permanente</strong><p><?= nl2br(htmlspecialchars($problem['permanent_solution']?:'Pendiente de definir.')) ?></p></div></div></div></section>

  <?php if(Auth::can('problems.manage')): ?><details class="card itsm-edit-details"><summary class="card-header">Editar problema</summary><div class="card-body"><form method="post" action="<?= APP_BASE_URL ?>/problems/update" data-single-submit class="itsm-editor-form"><input type="hidden" name="_csrf" value="<?= Csrf::token() ?>"><input type="hidden" name="problem_id" value="<?= (int)$problem['id'] ?>"><div class="grid grid-2"><label>Título<input class="form-control" name="title" value="<?= htmlspecialchars($problem['title']) ?>" required></label><label>Estado<select class="form-control" name="status"><?php foreach($statuses as $code=>$label): ?><option value="<?= $code ?>" <?= $problem['status']===$code?'selected':'' ?>><?= htmlspecialchars($label) ?></option><?php endforeach; ?></select></label></div><label>Descripción<textarea class="form-control" name="description" rows="4" required><?= htmlspecialchars($problem['description']) ?></textarea></label><div class="grid grid-3"><label>Categoría<select class="form-control" name="category_id"><option value="0">Sin categoría</option><?php foreach($categories as $c): ?><option value="<?= (int)$c['id'] ?>" <?= (int)$problem['category_id']===(int)$c['id']?'selected':'' ?>><?= htmlspecialchars($c['name']) ?></option><?php endforeach; ?></select></label><label>Parque<select class="form-control" name="park_id"><option value="0">General</option><?php foreach($parks as $p): ?><option value="<?= (int)$p['id'] ?>" <?= (int)$problem['park_id']===(int)$p['id']?'selected':'' ?>><?= htmlspecialchars($p['name']) ?></option><?php endforeach; ?></select></label><label>Propietario<select class="form-control" name="owner_user_id"><option value="0">Sin propietario</option><?php foreach($owners as $o): ?><option value="<?= (int)$o['id'] ?>" <?= (int)$problem['owner_user_id']===(int)$o['id']?'selected':'' ?>><?= htmlspecialchars($o['full_name']) ?></option><?php endforeach; ?></select></label></div><div class="itsm-learning-grid"><label>Causa raíz<textarea class="form-control" name="root_cause" rows="3"><?= htmlspecialchars((string)$problem['root_cause']) ?></textarea></label><label>Workaround<textarea class="form-control" name="workaround" rows="3"><?= htmlspecialchars((string)$problem['workaround']) ?></textarea></label><label>Solución permanente<textarea class="form-control" name="permanent_solution" rows="3"><?= htmlspecialchars((string)$problem['permanent_solution']) ?></textarea></label></div><button class="btn btn-primary" type="submit">Guardar cambios</button></form></div></details><?php endif; ?>

  <div class="grid grid-2">
    <section class="card"><div class="card-header">Tickets relacionados · <?= count($occurrences) ?></div><div class="card-body"><?php if(Auth::can('problems.manage')): ?><form class="itsm-inline-form" method="post" action="<?= APP_BASE_URL ?>/problems/link-ticket" data-single-submit><input type="hidden" name="_csrf" value="<?= Csrf::token() ?>"><input type="hidden" name="problem_id" value="<?= (int)$problem['id'] ?>"><select class="form-control" name="ticket_id" required><option value="">Selecciona un ticket existente</option><?php foreach(($availableTickets??[]) as $ticket): ?><option value="<?= (int)$ticket['id'] ?>"><?= htmlspecialchars($ticket['ticket_number'].' · '.$ticket['subject'].' · '.$ticket['park_name'].' · '.$ticket['category_name']) ?></option><?php endforeach; ?></select><button class="btn btn-primary" type="submit" <?= empty($availableTickets)?'disabled':'' ?>>Relacionar</button></form><?php if(empty($availableTickets)): ?><small class="field-help">No hay otros tickets disponibles para relacionar.</small><?php endif; ?><?php endif; ?><div class="itsm-related-list"><?php foreach($occurrences as $t): ?><div class="itsm-related-item"><a href="<?= APP_BASE_URL ?>/tickets/view?id=<?= (int)$t['id'] ?>"><strong><?= htmlspecialchars($t['ticket_number'].' · '.$t['subject']) ?></strong><small><?= htmlspecialchars($t['park_name']??'Sin parque') ?> · <?= htmlspecialchars($t['category_name']??'Sin categoría') ?> · <?= htmlspecialchars($t['status']) ?></small></a><?php if(Auth::can('problems.manage')): ?><form method="post" action="<?= APP_BASE_URL ?>/problems/unlink-ticket" data-single-submit><input type="hidden" name="_csrf" value="<?= Csrf::token() ?>"><input type="hidden" name="problem_id" value="<?= (int)$problem['id'] ?>"><input type="hidden" name="ticket_id" value="<?= (int)$t['id'] ?>"><button class="btn btn-outline-secondary btn-sm" type="submit">Quitar</button></form><?php endif; ?></div><?php endforeach; ?><?php if(!$occurrences): ?><div class="empty-state">Aún no hay tickets relacionados.</div><?php endif; ?></div></div></section>

    <section class="card"><div class="card-header">Conocimiento relacionado</div><div class="card-body"><?php if(Auth::can('problems.manage')&&$availableArticles): ?><form class="itsm-inline-form" method="post" action="<?= APP_BASE_URL ?>/problems/link-article" data-single-submit><input type="hidden" name="_csrf" value="<?= Csrf::token() ?>"><input type="hidden" name="problem_id" value="<?= (int)$problem['id'] ?>"><select class="form-control" name="article_id" required><option value="">Selecciona artículo</option><?php foreach($availableArticles as $a): ?><option value="<?= (int)$a['id'] ?>"><?= htmlspecialchars($a['article_number'].' · '.$a['title']) ?></option><?php endforeach; ?></select><label class="itsm-check"><input type="checkbox" name="is_primary" value="1"> Principal</label><button class="btn btn-primary" type="submit">Relacionar</button></form><?php endif; ?><div class="itsm-related-list"><?php foreach($articles as $a): ?><div class="itsm-related-item"><a href="<?= APP_BASE_URL ?>/knowledge/view?id=<?= (int)$a['id'] ?>"><strong><?= htmlspecialchars($a['article_number'].' · '.$a['title']) ?></strong><small><?= $a['is_primary']?'Solución principal · ':'' ?><?= htmlspecialchars($a['status']) ?> · <?= htmlspecialchars($a['visibility']) ?></small></a><?php if(Auth::can('problems.manage')): ?><form method="post" action="<?= APP_BASE_URL ?>/problems/unlink-article" data-single-submit><input type="hidden" name="_csrf" value="<?= Csrf::token() ?>"><input type="hidden" name="problem_id" value="<?= (int)$problem['id'] ?>"><input type="hidden" name="article_id" value="<?= (int)$a['id'] ?>"><button class="btn btn-outline-secondary btn-sm" type="submit">Quitar</button></form><?php endif; ?></div><?php endforeach; ?><?php if(!$articles): ?><div class="empty-state">No hay artículos relacionados todavía.</div><?php endif; ?></div></div></section>
  </div>

  <section class="card"><div class="card-header">Timeline del problema</div><div class="card-body"><div class="ticket-timeline"><?php foreach($timeline as $e): ?><div class="timeline-item"><span class="timeline-dot"></span><div><strong><?= htmlspecialchars(str_replace('_',' ',ucfirst(strtolower($e['action'])))) ?></strong><p><?= htmlspecialchars(date('d/m/Y H:i',strtotime($e['created_at']))) ?><?= !empty($e['actor_name'])?' · '.htmlspecialchars($e['actor_name']):'' ?></p></div></div><?php endforeach; ?><?php if(!$timeline): ?><div class="empty-state">Aún no hay cambios registrados.</div><?php endif; ?></div></div></section>
</div>
<?php require APP_ROOT.'/app/Views/shared/app_end.php'; ?>
