<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use App\Controllers\{AuthController,DashboardController,AdminController,AuditController,TicketController,TicketViewController,TicketFeedbackController,ManagementController,XlsxExportController,ExternalController,ResolutionController,ConversationController,SearchController,WorkflowController,ProblemController,KnowledgeController,HelpController,NotificationController,MailAdminController,SupportTeamController,ExternalReportController};
$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';
$base=rtrim(APP_PUBLIC_PATH,'/');
if(str_starts_with($path,$base))$path=substr($path,strlen($base))?:'/';
$path=strtolower($path);
$method=$_SERVER['REQUEST_METHOD']??'GET';
$routes=[
    ['GET','/',[TicketController::class,'publicHome']],
    ['GET','/crear-ticket',[TicketController::class,'publicCreate']],
    ['POST','/crear-ticket',[TicketController::class,'publicStore']],
    ['GET','/ticket-enviado',[TicketController::class,'publicDone']],
    ['GET','/mis-tickets',[TicketController::class,'index']],
    ['GET','/login',[AuthController::class,'home']],
    ['POST','/auth/request',[AuthController::class,'requestOtp']],
    ['GET','/register',[AuthController::class,'register']],
    ['POST','/auth/register',[AuthController::class,'createUser']],
    ['GET','/otp',[AuthController::class,'otp']],
    ['POST','/auth/verify',[AuthController::class,'verify']],
    ['POST','/auth/resend',[AuthController::class,'resend']],
    ['POST','/logout',[AuthController::class,'logout']],
    ['GET','/dashboard',[DashboardController::class,'index']],
    ['GET','/buscar',[SearchController::class,'index']],
    ['GET','/manual',[HelpController::class,'manual']],
    ['POST','/notifications/read',[NotificationController::class,'read']],
    ['POST','/notifications/read-all',[NotificationController::class,'readAll']],
    ['GET','/tickets',[TicketController::class,'index']],
    ['GET','/tickets/queue',[TicketController::class,'queue']],
    ['GET','/tickets/view',[TicketViewController::class,'show']],
    ['GET','/tickets/feedback',[TicketFeedbackController::class,'index']],
    ['POST','/tickets/feedback',[TicketFeedbackController::class,'submit']],
    ['POST','/tickets/feedback/reopen',[TicketFeedbackController::class,'reopen']],
    ['POST','/tickets/claim',[TicketController::class,'claim']],
    ['POST','/tickets/assign',[TicketController::class,'assign']],
    ['POST','/tickets/release',[TicketController::class,'release']],
    ['POST','/tickets/status',[WorkflowController::class,'changeStatus']],
    ['GET','/tickets/resolve',[ResolutionController::class,'index']],
    ['POST','/tickets/resolve',[ResolutionController::class,'store']],
    ['POST','/tickets/respond',[ConversationController::class,'respond']],
    ['GET','/tickets/attachment',[ConversationController::class,'download']],

    ['GET','/problems',[ProblemController::class,'index']],
    ['GET','/problems/new',[ProblemController::class,'form']],
    ['GET','/problems/create',[ProblemController::class,'form']],
    ['POST','/problems/create',[ProblemController::class,'create']],
    ['GET','/problems/view',[ProblemController::class,'view']],
    ['POST','/problems/update',[ProblemController::class,'update']],
    ['POST','/problems/link-ticket',[ProblemController::class,'linkTicket']],
    ['POST','/problems/unlink-ticket',[ProblemController::class,'unlinkTicket']],
    ['POST','/problems/link-article',[ProblemController::class,'linkArticle']],
    ['POST','/problems/unlink-article',[ProblemController::class,'unlinkArticle']],

    ['GET','/knowledge',[KnowledgeController::class,'index']],
    ['GET','/knowledge/new',[KnowledgeController::class,'form']],
    ['GET','/knowledge/create',[KnowledgeController::class,'form']],
    ['GET','/knowledge/gestion',[KnowledgeController::class,'index']],
    ['GET','/knowledge/edit',[KnowledgeController::class,'form']],
    ['POST','/knowledge/create',[KnowledgeController::class,'create']],
    ['POST','/knowledge/update',[KnowledgeController::class,'update']],
    ['GET','/knowledge/view',[KnowledgeController::class,'view']],
    ['POST','/knowledge/publish',[KnowledgeController::class,'publish']],
    ['POST','/knowledge/archive',[KnowledgeController::class,'archive']],

    ['GET','/gestion',[ManagementController::class,'dashboard']],
    ['GET','/gestion/informes',[ManagementController::class,'reports']],
    ['GET','/gestion/informes/exportar',[XlsxExportController::class,'export']],
    ['GET','/gestion/equipo',[SupportTeamController::class,'index']],
    ['GET','/gestion/equipo/exportar',[SupportTeamController::class,'export']],
    ['POST','/gestion/equipo/agregar',[SupportTeamController::class,'addMember']],
    ['POST','/gestion/equipo/retirar',[SupportTeamController::class,'removeMember']],
    ['GET','/admin/users',[AdminController::class,'users']],
    ['POST','/admin/users/create',[AdminController::class,'create']],
    ['POST','/admin/users/assign',[AdminController::class,'assign']],
    ['POST','/admin/users/delete',[AdminController::class,'delete']],
    ['GET','/admin/externos',[ExternalController::class,'index']],
    ['GET','/admin/externos/informe',[ExternalReportController::class,'index']],
    ['GET','/admin/externos/informe/exportar',[ExternalReportController::class,'export']],
    ['POST','/admin/users/convertir-externo',[ExternalController::class,'convertInternal']],
    ['POST','/admin/externos/actualizar',[ExternalController::class,'updateUser']],
    ['POST','/admin/externos/desactivar',[ExternalController::class,'deactivateUser']],
    ['POST','/admin/externos/crear',[ExternalController::class,'createUser']],
    ['POST','/admin/externos/asignar',[ExternalController::class,'grant']],
    ['POST','/admin/externos/revocar',[ExternalController::class,'revoke']],
    ['GET','/admin/audit',[AuditController::class,'index']],
    ['GET','/admin/correo',[MailAdminController::class,'index']],
    ['POST','/admin/correo/probar',[MailAdminController::class,'test']],
    ['POST','/admin/correo/reintentar',[MailAdminController::class,'retry']],
];
foreach($routes as [$m,$p,$h]){
    if($method===$m&&$path===$p){[$c,$a]=$h;(new $c())->$a();exit;}
}
http_response_code(404);
\App\Core\View::render('errors/friendly',['user'=>\App\Core\Auth::user(),'title'=>'Página no disponible','message'=>'La página que intentaste abrir no está disponible o cambió de ubicación.']);