<?php
use App\Core\Csrf;
$priorityLabels=$priorityLabels??['LOW'=>'Baja','MEDIUM'=>'Media','HIGH'=>'Alta','CRITICAL'=>'Crítica'];
$statusLabels=$statusLabels??[];$myTickets=$myTickets??[];
$pageTitle='Centro de soporte';$pageSection='Centro de soporte';$activeNav='support';$helpContext='support_center';
require APP_ROOT.'/app/Views/shared/app_start.php';
?>
<div class="support-page">
<div class="page-heading"><div><div class="ticket-kicker">Equipo de soporte</div><h1 class="page-title">Centro de soporte</h1><p class="page-subtitle">Primero continúa lo que ya tienes; después toma un caso nuevo.</p></div></div>
<?php if(!empty($flash)): ?><div class="alert"><?= htmlspecialchars($flash['message']) ?></div><?php endif; ?>
<section class="support-section"><div class="support-section-heading"><div><h2>Mis casos activos</h2><p>Casos que ya están bajo tu responsabilidad.</p></div><span class="support-count"><?= count($myTickets) ?></span></div>
<?php if($myTickets): ?><div class="support-case-list"><?php foreach($myTickets as $t): ?><article class="support-case-card support-case-mine"><div class="support-case-main"><div class="support-case-title"><span class="ticket-number-small"><?= htmlspecialchars($t['ticket_number']) ?></span><h2><?= htmlspecialchars($t['subject']) ?></h2></div><span class="ticket-status-pill status-<?= strtolower((string)$t['status']) ?>"><?= htmlspecialchars($statusLabels[$t['status']]??$t['status']) ?></span></div><div class="support-case-meta"><span><?= htmlspecialchars($t['park_name']??'Ubicación no especificada') ?></span><span><?= htmlspecialchars($t['category_name']??'Sin categoría') ?></span><span>Prioridad <?= htmlspecialchars(strtolower($priorityLabels[$t['priority']]??$t['priority'])) ?></span></div><div class="support-case-actions"><a class="btn btn-primary" href="<?= APP_BASE_URL ?>/tickets/view?id=<?= (int)$t['id'] ?>">Continuar atención</a></div></article><?php endforeach; ?></div><?php else: ?><div class="support-inline-empty">No tienes casos activos.</div><?php endif; ?></section>
<section class="support-section"><div class="support-section-heading"><div><h2>Casos por atender</h2><p>Toma uno únicamente cuando puedas comenzar a atenderlo.</p></div><span class="support-count"><?= count($tickets) ?></span></div>
<?php if($tickets): ?><div class="support-case-list"><?php foreach($tickets as $t): ?><article class="support-case-card"><div class="support-case-main"><div class="support-case-title"><span class="ticket-number-small"><?= htmlspecialchars($t['ticket_number']) ?></span><h2><?= htmlspecialchars($t['subject']) ?></h2></div><span class="priority-chip priority-<?= strtolower((string)$t['priority']) ?>"><?= htmlspecialchars($priorityLabels[$t['priority']]??$t['priority']) ?></span></div><div class="support-case-meta"><span><?= htmlspecialchars($t['park_name']??'Ubicación no especificada') ?></span><span><?= htmlspecialchars($t['category_name']??'Sin categoría') ?></span><span><?= htmlspecialchars(date('d/m/Y H:i',strtotime($t['created_at']))) ?></span></div><div class="support-case-actions"><a class="btn btn-outline-secondary" href="<?= APP_BASE_URL ?>/tickets/view?id=<?= (int)$t['id'] ?>">Ver antes</a><form method="post" action="<?= APP_BASE_URL ?>/tickets/claim" data-single-submit><input type="hidden" name="_csrf" value="<?= Csrf::token() ?>"><input type="hidden" name="ticket_id" value="<?= (int)$t['id'] ?>"><button class="btn btn-primary" type="submit">Tomar y atender</button></form></div></article><?php endforeach; ?></div><?php else: ?><div class="support-inline-empty">No hay casos esperando atención.</div><?php endif; ?></section>
</div>
<?php require APP_ROOT.'/app/Views/shared/app_end.php'; ?>