<?php
use App\Core\{Auth,Csrf,Database};

$statusLabels=$statusLabels??[];$status=(string)$ticket['status'];
$comments=[];$attachmentsByComment=[];$looseAttachments=[];$canComment=false;$canUpload=false;$resolution=null;
try{
    $pdo=Database::pdo();
    $aq=$pdo->prepare("SELECT can_comment,can_upload FROM external_ticket_access WHERE ticket_id=? AND user_id=? AND revoked_at IS NULL LIMIT 1");$aq->execute([(int)$ticket['id'],(int)Auth::id()]);$access=$aq->fetch();$canComment=(bool)($access['can_comment']??false);$canUpload=(bool)($access['can_upload']??false);
    $cq=$pdo->prepare("SELECT tc.*,COALESCE(NULLIF(u.full_name,''),NULLIF(tc.author_name,''),'Usuario') author_display_name,u.access_type author_access_type,r.code author_role,ep.organization_name author_organization FROM ticket_comments tc LEFT JOIN users u ON u.id=tc.author_user_id LEFT JOIN roles r ON r.id=u.role_id LEFT JOIN external_profiles ep ON ep.user_id=u.id WHERE tc.ticket_id=? AND tc.deleted_at IS NULL AND tc.visibility IN('PUBLIC','EXTERNAL') ORDER BY tc.created_at,tc.id");$cq->execute([(int)$ticket['id']]);$comments=$cq->fetchAll();
    $at=$pdo->prepare("SELECT ta.* FROM ticket_attachments ta WHERE ta.ticket_id=? AND ta.visibility IN('PUBLIC','EXTERNAL') ORDER BY ta.created_at,ta.id");$at->execute([(int)$ticket['id']]);foreach($at->fetchAll() as $file){if(!empty($file['comment_id']))$attachmentsByComment[(int)$file['comment_id']][]=$file;else $looseAttachments[]=$file;}
    $rq=$pdo->prepare("SELECT tr.solution_applied,tr.preventive_action,tr.updated_at,u.full_name resolved_by_name FROM ticket_resolutions tr LEFT JOIN users u ON u.id=tr.resolved_by WHERE tr.ticket_id=? LIMIT 1");$rq->execute([(int)$ticket['id']]);$resolution=$rq->fetch()?:null;
}catch(\Throwable $e){}

$pageTitle=$ticket['ticket_number'];$pageSection='Mis casos';$activeNav='mine';$helpContext='ticket';require APP_ROOT.'/app/Views/shared/app_start.php';
?>
<div class="external-workspace" data-external-workspace>
  <div class="external-case-head"><div><div class="ticket-kicker">Caso <?= htmlspecialchars($ticket['ticket_number']) ?></div><h1 class="page-title"><?= htmlspecialchars($ticket['subject']) ?></h1><div class="external-case-meta"><span class="external-state-chip"><?= htmlspecialchars($statusLabels[$status]??str_replace('_',' ',$status)) ?></span><span><?= htmlspecialchars($ticket['park_name']??'Ubicación no especificada') ?></span><span><?= htmlspecialchars($ticket['category_name']??'Sin categoría') ?></span></div></div><a class="btn btn-outline-secondary" href="<?= APP_BASE_URL ?>/mis-tickets">Mis casos</a></div>
  <?php if(!empty($flash)): ?><div class="alert alert-success"><?= htmlspecialchars($flash['message']) ?></div><?php endif; ?>

  <div class="external-work-grid"><main class="external-work-main">
    <section class="card external-problem-card"><div class="card-body"><div class="external-section-head"><div><span class="ticket-kicker">Lo que necesitamos</span><h2>Qué está pasando</h2><p>Revisa el problema antes de enviar una actualización.</p></div><span class="external-responsible"><?= !empty($ticket['assigned_name'])?'Responsable: '.htmlspecialchars($ticket['assigned_name']):'Pendiente de atención' ?></span></div><div class="external-problem-primary"><span>Problema reportado</span><p><?= nl2br(htmlspecialchars($ticket['description'])) ?></p></div><div class="external-problem-facts external-problem-facts-secondary"><div><span>Ubicación</span><strong><?= htmlspecialchars($ticket['park_name']??'No especificada') ?></strong><small><?= htmlspecialchars($ticket['area_name']??'Área no especificada') ?></small></div><div><span>Tipo</span><strong><?= htmlspecialchars($ticket['category_name']??'No especificado') ?></strong></div></div></div></section>

    <section class="card external-conversation-card" id="conversacion"><div class="card-body"><div class="external-section-head"><div><span class="ticket-kicker">Seguimiento</span><h2>Conversación con soporte</h2><p>Aquí quedan los mensajes y archivos que puedes consultar durante tu participación.</p></div><span class="external-message-count"><?= count($comments)+count($looseAttachments) ?> actualización(es)</span></div><div class="conversation-list external-conversation-list">
      <?php foreach($comments as $c):
        $mine=(int)($c['author_user_id']??0)===(int)Auth::id();
        $fromExternal=(($c['author_access_type']??'')==='EXTERNAL');
        $fromRequester=((int)($c['author_user_id']??0)>0&&(int)($c['author_user_id']??0)===(int)($ticket['requester_user_id']??0))||(!empty($c['author_email'])&&strtolower((string)$c['author_email'])===strtolower((string)($ticket['requester_email']??'')));
        $externalChannel=(string)$c['visibility']==='EXTERNAL';
        $authorName=trim((string)($c['author_display_name']??$c['author_name']??''));
        if($authorName==='')$authorName=$mine?'Tú':($fromExternal?'Colaborador':($fromRequester?'Solicitante':'Equipo de soporte'));
        if($fromExternal){
            $authorRole='Colaborador';
            if(!empty($c['author_organization']))$authorRole.=' · '.trim((string)$c['author_organization']);
        }elseif($fromRequester){
            $authorRole='Solicitante';
        }else{
            $authorRole='Equipo de soporte';
        }
        if($mine)$authorRole='Tú · '.$authorRole;
        $channel=$externalChannel?'Colaboración':'Seguimiento';
      ?>
      <article class="conversation-message <?= $mine?'is-mine ':'' ?><?= $externalChannel?'is-external':'is-requester' ?>"><div class="conversation-channel-label <?= $externalChannel?'external':'support' ?>"><?= htmlspecialchars($channel) ?></div><div class="conversation-meta"><strong><?= htmlspecialchars($authorName) ?></strong><span class="conversation-author-role"><?= htmlspecialchars($authorRole) ?></span><span><?= htmlspecialchars(date('d/m/Y H:i',strtotime($c['created_at']))) ?></span></div><p><?= nl2br(htmlspecialchars($c['body'])) ?></p><?php foreach($attachmentsByComment[(int)$c['id']]??[] as $f): ?><a class="conversation-file" href="<?= APP_BASE_URL ?>/tickets/attachment?id=<?= (int)$f['id'] ?>">📎 <?= htmlspecialchars($f['original_name']) ?> <small><?= number_format(((int)$f['size_bytes'])/1024,0) ?> KB</small></a><?php endforeach; ?></article>
      <?php endforeach; ?>
      <?php foreach($looseAttachments as $f): ?><article class="conversation-message"><div class="conversation-meta"><strong>Archivo compartido</strong><span><?= htmlspecialchars(date('d/m/Y H:i',strtotime($f['created_at']))) ?></span></div><a class="conversation-file" href="<?= APP_BASE_URL ?>/tickets/attachment?id=<?= (int)$f['id'] ?>">📎 <?= htmlspecialchars($f['original_name']) ?></a></article><?php endforeach; ?>
      <?php if(!$comments&&!$looseAttachments): ?><div class="external-empty-conversation"><strong>Aún no hay actualizaciones</strong><span>Cuando exista un avance aparecerá aquí.</span></div><?php endif; ?>
    </div></div></section>

    <?php if($canComment||$canUpload): ?><section class="card external-reply-card" id="responder"><div class="card-body"><div class="external-section-head"><div><span class="ticket-kicker">Tu actualización</span><h2>Responder</h2><p>Comparte solo lo necesario para continuar el caso.</p></div></div><div class="external-quick-actions" aria-label="Ayudas de respuesta"><?php if($canComment): ?><button type="button" class="external-quick-btn" data-external-template="Avance:">Enviar avance</button><button type="button" class="external-quick-btn" data-external-template="Necesito información adicional:">Solicitar información</button><button type="button" class="external-quick-btn is-success" data-external-template="Trabajo realizado / listo para revisión:">Trabajo realizado</button><?php endif; ?></div><form class="external-response-form" method="post" action="<?= APP_BASE_URL ?>/tickets/respond" enctype="multipart/form-data" data-single-submit data-action-message="Enviando actualización…"><input type="hidden" name="_csrf" value="<?= Csrf::token() ?>"><input type="hidden" name="ticket_id" value="<?= (int)$ticket['id'] ?>"><input type="hidden" name="visibility" value="EXTERNAL"><?php if($canComment): ?><label>Mensaje<textarea class="form-control" name="body" rows="5" data-external-message placeholder="Describe el avance, resultado o información que necesitas."></textarea></label><?php endif; ?><?php if($canUpload): ?><label class="external-upload-label">Archivo <span class="subtle">Opcional · máximo 10 MB</span><input class="external-file-input" type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png,.webp,.txt,.doc,.docx,.xls,.xlsx"></label><?php endif; ?><div class="external-send-row"><span><?= $canComment&&$canUpload?'Puedes enviar mensaje, archivo o ambos.':($canComment?'El equipo de soporte recibirá tu actualización.':'Puedes adjuntar evidencia para este caso.') ?></span><button class="btn btn-primary" type="submit">Enviar actualización</button></div></form></div></section><?php endif; ?>

    <?php if($resolution): ?><section class="card external-solution-card"><div class="card-body"><span class="ticket-kicker">Resultado</span><h2>Solución final</h2><div class="external-problem-primary"><p><?= nl2br(htmlspecialchars((string)$resolution['solution_applied'])) ?></p></div><?php if(!empty($resolution['preventive_action'])): ?><div class="dashboard-scope-note"><strong>Recomendación</strong><span><?= nl2br(htmlspecialchars((string)$resolution['preventive_action'])) ?></span></div><?php endif; ?><div class="subtle" style="margin-top:10px"><?= !empty($resolution['resolved_by_name'])?htmlspecialchars((string)$resolution['resolved_by_name']).' · ':'' ?><?= htmlspecialchars(date('d/m/Y H:i',strtotime((string)$resolution['updated_at']))) ?></div></div></section><?php endif; ?>
  </main>

  <aside class="external-work-side"><section class="card external-side-card"><div class="card-body"><span class="ticket-kicker">Qué sigue</span><h2>Flujo del caso</h2><ol class="external-next-steps"><li><span>1</span><div><strong>Revisa</strong><small>Lee el problema y el seguimiento.</small></div></li><li><span>2</span><div><strong>Actualiza</strong><small>Responde o adjunta evidencia cuando sea necesario.</small></div></li><li><span>3</span><div><strong>Consulta el resultado</strong><small>La solución final aparecerá en este mismo caso.</small></div></li></ol></div></section></aside></div>
</div>
<script nonce="<?= htmlspecialchars(CSP_NONCE) ?>">document.querySelectorAll('[data-external-template]').forEach(function(button){button.addEventListener('click',function(){const field=document.querySelector('[data-external-message]');if(!field)return;const template=(button.getAttribute('data-external-template')||'').trim();const prefix=template+'\n';if(!field.value.trim())field.value=prefix;else if(!field.value.startsWith(template))field.value=prefix+field.value;field.focus();field.setSelectionRange(field.value.length,field.value.length);});});</script>
<?php require APP_ROOT.'/app/Views/shared/app_end.php'; ?>