<?php
$pageTitle='Informes';$pageSection='Gestión';$activeNav='reports';$helpContext='reports';
require APP_ROOT.'/app/Views/shared/app_start.php';
$statusLabels=['NEW'=>'Nuevo','AVAILABLE'=>'Disponible','IN_PROGRESS'=>'En proceso','PENDING'=>'En espera','RESOLVED'=>'Resuelto','CLOSED'=>'Cerrado','REOPENED'=>'Reabierto','CANCELLED'=>'Cancelado'];
$priorityLabels=['LOW'=>'Baja','MEDIUM'=>'Media','HIGH'=>'Alta','CRITICAL'=>'Crítica'];
$resolutionLabels=['CONFIGURATION'=>'Configuración','RESTART'=>'Reinicio','REPLACEMENT'=>'Cambio / reemplazo','PROVIDER'=>'Gestión con proveedor','USER_GUIDANCE'=>'Orientación al usuario','SOFTWARE'=>'Software','NETWORK'=>'Red / conectividad','HARDWARE'=>'Hardware','PERMISSION'=>'Acceso / permisos','MAINTENANCE'=>'Mantenimiento','OTHER'=>'Otro'];
$q=http_build_query($filters);$documented=0;foreach($rows as $r)if(!empty($r['solution_applied']))$documented++;
?>
<link rel="stylesheet" href="<?= htmlspecialchars(APP_PUBLIC_PATH) ?>/assets/css/management.css">
<div class="mgmt-head"><div><span class="mgmt-kicker">Reportería y aprendizaje</span><h1>Informes de tickets</h1><p>No solo contamos casos: registramos qué los causó y cómo se resolvieron para poder reutilizar la experiencia.</p></div><div class="mgmt-head-actions"><a class="btn btn-outline-secondary" href="<?= APP_BASE_URL ?>/gestion?<?= htmlspecialchars($q) ?>">← Dashboard</a><a class="btn btn-primary" href="<?= APP_BASE_URL ?>/gestion/informes/exportar?<?= htmlspecialchars($q) ?>">Descargar CSV</a></div></div>
<div class="mgmt-kpi-grid report-learning-kpis"><article class="mgmt-kpi"><span>Tickets mostrados</span><strong><?= count($rows) ?></strong><small>Según el filtro actual</small></article><article class="mgmt-kpi"><span>Soluciones documentadas</span><strong><?= $documented ?></strong><small><?= count($rows)>0?round(($documented/count($rows))*100,1):0 ?>% del resultado</small></article></div>
<form class="mgmt-filterbar" method="get" action="<?= APP_BASE_URL ?>/gestion/informes" data-processing-form>
<label>Desde<input class="form-control" type="date" name="from" value="<?= htmlspecialchars($filters['from']) ?>"></label><label>Hasta<input class="form-control" type="date" name="to" value="<?= htmlspecialchars($filters['to']) ?>"></label>
<label>Parque<select class="form-control" name="park_id"><option value="0">Todos</option><?php foreach($parks as $x): ?><option value="<?= (int)$x['id'] ?>" <?= (int)$filters['park_id']===(int)$x['id']?'selected':'' ?>><?= htmlspecialchars($x['name']) ?></option><?php endforeach; ?></select></label>
<label>Categoría<select class="form-control" name="category_id"><option value="0">Todas</option><?php foreach($categories as $x): ?><option value="<?= (int)$x['id'] ?>" <?= (int)$filters['category_id']===(int)$x['id']?'selected':'' ?>><?= htmlspecialchars($x['name']) ?></option><?php endforeach; ?></select></label>
<label>Responsable<select class="form-control" name="assigned_to"><option value="0">Todos</option><?php foreach($supportUsers as $x): ?><option value="<?= (int)$x['id'] ?>" <?= (int)$filters['assigned_to']===(int)$x['id']?'selected':'' ?>><?= htmlspecialchars($x['full_name']) ?></option><?php endforeach; ?></select></label>
<label>Estado<select class="form-control" name="status"><option value="">Todos</option><?php foreach($statusLabels as $k=>$v): ?><option value="<?= $k ?>" <?= $filters['status']===$k?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></label>
<label>Prioridad<select class="form-control" name="priority"><option value="">Todas</option><?php foreach($priorityLabels as $k=>$v): ?><option value="<?= $k ?>" <?= $filters['priority']===$k?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></label>
<div class="mgmt-filter-actions"><button class="btn btn-primary">Aplicar filtros</button><a class="btn btn-outline-secondary" href="<?= APP_BASE_URL ?>/gestion/informes">Limpiar</a></div></form>
<section class="mgmt-card"><div class="mgmt-card-head"><div><span>Resultado</span><h2><?= count($rows) ?> registros mostrados</h2></div><small class="muted">La vista limita a 500 filas; la exportación incluye todo el filtro.</small></div><div class="table-responsive"><table class="table report-table"><thead><tr><th>Ticket</th><th>Fecha</th><th>Solicitante</th><th>Parque</th><th>Categoría</th><th>Asunto</th><th>Estado</th><th>Responsable</th><th>Resolución / aprendizaje</th><th>Resuelto</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><a href="<?= APP_BASE_URL ?>/tickets/view?id=<?= (int)$r['id'] ?>"><strong><?= htmlspecialchars($r['ticket_number']) ?></strong></a><small><?= htmlspecialchars($priorityLabels[$r['priority']]??$r['priority']) ?></small></td><td><?= htmlspecialchars(date('d/m/Y H:i',strtotime($r['created_at']))) ?></td><td><?= htmlspecialchars($r['requester_name']) ?><small><?= htmlspecialchars($r['requester_email']) ?></small></td><td><?= htmlspecialchars($r['park_name']??'—') ?><small><?= htmlspecialchars($r['area_name']??'') ?></small></td><td><?= htmlspecialchars($r['category_name']??'—') ?></td><td><?= htmlspecialchars($r['subject']) ?></td><td><?= htmlspecialchars($statusLabels[$r['status']]??$r['status']) ?></td><td><?= htmlspecialchars($r['assigned_name']??'Sin asignar') ?></td><td class="report-resolution"><?php if(!empty($r['solution_applied'])):?><details><summary><?= htmlspecialchars($resolutionLabels[$r['resolution_type']]??'Ver solución') ?></summary><div><strong>Causa</strong><p><?= nl2br(htmlspecialchars($r['root_cause']??'No indicada')) ?></p><strong>Solución aplicada</strong><p><?= nl2br(htmlspecialchars($r['solution_applied'])) ?></p><?php if(!empty($r['preventive_action'])):?><strong>Prevención</strong><p><?= nl2br(htmlspecialchars($r['preventive_action'])) ?></p><?php endif; ?><small>Documentado por <?= htmlspecialchars($r['resolution_author']??'equipo de soporte') ?><?= !empty($r['is_reusable'])?' · Reutilizable':'' ?></small></div></details><?php else: ?><span class="muted">Sin documentar</span><?php endif; ?></td><td><?= $r['resolved_at']?htmlspecialchars(date('d/m/Y H:i',strtotime($r['resolved_at']))):'—' ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<div class="processing-overlay" data-processing-overlay hidden><div class="processing-box"><div class="processing-spinner"></div><h2>Procesando información</h2><p>Aplicando filtros al informe…</p><div class="processing-line"><i></i></div><small>Preparando el detalle solicitado.</small></div></div><script>document.querySelectorAll('[data-processing-form]').forEach(f=>f.addEventListener('submit',()=>{const x=document.querySelector('[data-processing-overlay]');if(x)x.hidden=false;}));</script>
<style>.report-learning-kpis{grid-template-columns:repeat(2,minmax(0,1fr));max-width:720px}.report-resolution{min-width:260px}.report-resolution summary{cursor:pointer;font-weight:800;color:#1945a3}.report-resolution details>div{padding:.65rem 0}.report-resolution p{margin:.15rem 0 .65rem;white-space:normal;max-width:420px}@media(max-width:700px){.report-learning-kpis{grid-template-columns:1fr}}</style>
<?php require APP_ROOT.'/app/Views/shared/app_end.php'; ?>