<?php
$pageTitle='Informes';$pageSection='Gestión';$activeNav='reports';$helpContext='reports';
require APP_ROOT.'/app/Views/shared/app_start.php';
$statusLabels=['NEW'=>'Nuevo','AVAILABLE'=>'Disponible','IN_PROGRESS'=>'En proceso','PENDING'=>'En espera','RESOLVED'=>'Resuelto','CLOSED'=>'Cerrado','REOPENED'=>'Reabierto','CANCELLED'=>'Cancelado'];
$priorityLabels=['LOW'=>'Baja','MEDIUM'=>'Media','HIGH'=>'Alta','CRITICAL'=>'Crítica'];
$q=http_build_query($filters);
?>
<link rel="stylesheet" href="<?= htmlspecialchars(APP_PUBLIC_PATH) ?>/assets/css/management.css">
<div class="mgmt-head"><div><span class="mgmt-kicker">Reportería</span><h1>Informes de tickets</h1><p>Filtra, revisa el detalle y exporta la información para análisis o presentación.</p></div><div class="mgmt-head-actions"><a class="btn btn-outline-secondary" href="<?= APP_BASE_URL ?>/gestion?<?= htmlspecialchars($q) ?>">← Dashboard</a><a class="btn btn-primary" href="<?= APP_BASE_URL ?>/gestion/informes/exportar?<?= htmlspecialchars($q) ?>">Descargar CSV</a></div></div>
<form class="mgmt-filterbar" method="get" action="<?= APP_BASE_URL ?>/gestion/informes" data-processing-form>
<label>Desde<input class="form-control" type="date" name="from" value="<?= htmlspecialchars($filters['from']) ?>"></label><label>Hasta<input class="form-control" type="date" name="to" value="<?= htmlspecialchars($filters['to']) ?>"></label>
<label>Parque<select class="form-control" name="park_id"><option value="0">Todos</option><?php foreach($parks as $x): ?><option value="<?= (int)$x['id'] ?>" <?= (int)$filters['park_id']===(int)$x['id']?'selected':'' ?>><?= htmlspecialchars($x['name']) ?></option><?php endforeach; ?></select></label>
<label>Categoría<select class="form-control" name="category_id"><option value="0">Todas</option><?php foreach($categories as $x): ?><option value="<?= (int)$x['id'] ?>" <?= (int)$filters['category_id']===(int)$x['id']?'selected':'' ?>><?= htmlspecialchars($x['name']) ?></option><?php endforeach; ?></select></label>
<label>Responsable<select class="form-control" name="assigned_to"><option value="0">Todos</option><?php foreach($supportUsers as $x): ?><option value="<?= (int)$x['id'] ?>" <?= (int)$filters['assigned_to']===(int)$x['id']?'selected':'' ?>><?= htmlspecialchars($x['full_name']) ?></option><?php endforeach; ?></select></label>
<label>Estado<select class="form-control" name="status"><option value="">Todos</option><?php foreach($statusLabels as $k=>$v): ?><option value="<?= $k ?>" <?= $filters['status']===$k?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></label>
<label>Prioridad<select class="form-control" name="priority"><option value="">Todas</option><?php foreach($priorityLabels as $k=>$v): ?><option value="<?= $k ?>" <?= $filters['priority']===$k?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></label>
<div class="mgmt-filter-actions"><button class="btn btn-primary">Aplicar filtros</button><a class="btn btn-outline-secondary" href="<?= APP_BASE_URL ?>/gestion/informes">Limpiar</a></div></form>
<section class="mgmt-card"><div class="mgmt-card-head"><div><span>Resultado</span><h2><?= count($rows) ?> registros mostrados</h2></div><small class="muted">La vista limita a 500 filas; la exportación incluye todo el filtro.</small></div><div class="table-responsive"><table class="table report-table"><thead><tr><th>Ticket</th><th>Fecha</th><th>Solicitante</th><th>Parque</th><th>Área</th><th>Categoría</th><th>Asunto</th><th>Prioridad</th><th>Estado</th><th>Responsable</th><th>1ª respuesta</th><th>Resuelto</th><th>Vence SLA</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><a href="<?= APP_BASE_URL ?>/tickets/view?id=<?= (int)$r['id'] ?>"><strong><?= htmlspecialchars($r['ticket_number']) ?></strong></a></td><td><?= htmlspecialchars(date('d/m/Y H:i',strtotime($r['created_at']))) ?></td><td><?= htmlspecialchars($r['requester_name']) ?><small><?= htmlspecialchars($r['requester_email']) ?></small></td><td><?= htmlspecialchars($r['park_name']??'—') ?></td><td><?= htmlspecialchars($r['area_name']??'—') ?></td><td><?= htmlspecialchars($r['category_name']??'—') ?></td><td><?= htmlspecialchars($r['subject']) ?></td><td><?= htmlspecialchars($priorityLabels[$r['priority']]??$r['priority']) ?></td><td><?= htmlspecialchars($statusLabels[$r['status']]??$r['status']) ?></td><td><?= htmlspecialchars($r['assigned_name']??'Sin asignar') ?></td><td><?= $r['first_response_at']?htmlspecialchars(date('d/m/Y H:i',strtotime($r['first_response_at']))):'—' ?></td><td><?= $r['resolved_at']?htmlspecialchars(date('d/m/Y H:i',strtotime($r['resolved_at']))):'—' ?></td><td><?= $r['resolution_due_at']?htmlspecialchars(date('d/m/Y H:i',strtotime($r['resolution_due_at']))):'—' ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<div class="processing-overlay" data-processing-overlay hidden><div class="processing-box"><div class="processing-spinner"></div><h2>Procesando información</h2><p>Aplicando filtros al informe…</p><div class="processing-line"><i></i></div><small>Preparando el detalle solicitado.</small></div></div><script>document.querySelectorAll('[data-processing-form]').forEach(f=>f.addEventListener('submit',()=>{const x=document.querySelector('[data-processing-overlay]');if(x)x.hidden=false;}));</script>
<?php require APP_ROOT.'/app/Views/shared/app_end.php'; ?>