<?php
use App\Core\{Auth,Csrf};
$pageTitle=$article['article_number'];$pageSection='Base de conocimiento';$activeNav='knowledge';$helpContext='knowledge';
require APP_ROOT.'/app/Views/shared/app_start.php';
?>
<div class="itsm-page knowledge-article-page">
  <div class="page-heading"><div><span class="ticket-kicker"><?= htmlspecialchars($article['article_number']) ?></span><h1 class="page-title"><?= htmlspecialchars($article['title']) ?></h1><p class="page-subtitle"><?= htmlspecialchars($statuses[$article['status']]??$article['status']) ?> · <?= htmlspecialchars($visibility[$article['visibility']]??$article['visibility']) ?> · <?= htmlspecialchars($article['category_name']??'Sin categoría') ?></p></div><div class="topbar-actions"><a class="btn btn-outline-secondary" href="<?= APP_BASE_URL ?>/knowledge">← Volver</a><?php if($canManage): ?><a class="btn btn-primary" href="<?= APP_BASE_URL ?>/knowledge/edit?id=<?= (int)$article['id'] ?>">Editar</a><?php endif; ?></div></div>
  <?php if(!empty($flash)): ?><div class="alert alert-success"><?= htmlspecialchars($flash['message']) ?></div><?php endif; ?>
  <?php if($canManage): ?><section class="card knowledge-state-bar"><div class="card-body"><div><strong>Estado editorial</strong><span><?= htmlspecialchars($statuses[$article['status']]??$article['status']) ?> · <?= htmlspecialchars($visibility[$article['visibility']]??$article['visibility']) ?></span></div><div class="topbar-actions"><?php if($article['status']!=='PUBLISHED'): ?><form method="post" action="<?= APP_BASE_URL ?>/knowledge/publish" data-single-submit><input type="hidden" name="_csrf" value="<?= Csrf::token() ?>"><input type="hidden" name="article_id" value="<?= (int)$article['id'] ?>"><button class="btn btn-primary" type="submit">Publicar</button></form><?php endif; ?><?php if($article['status']!=='ARCHIVED'): ?><form method="post" action="<?= APP_BASE_URL ?>/knowledge/archive" data-single-submit><input type="hidden" name="_csrf" value="<?= Csrf::token() ?>"><input type="hidden" name="article_id" value="<?= (int)$article['id'] ?>"><button class="btn btn-outline-secondary" type="submit">Archivar</button></form><?php endif; ?></div></div></section><?php endif; ?>
  <div class="knowledge-layout"><article class="card"><div class="card-body"><span class="ticket-kicker">Resumen</span><p class="knowledge-summary"><?= nl2br(htmlspecialchars($article['summary']?:'Sin resumen adicional.')) ?></p><div class="knowledge-content"><?= nl2br(htmlspecialchars($article['content'])) ?></div></div></article><aside class="card"><div class="card-body"><dl class="case-status-list"><div><dt>Autor</dt><dd><?= htmlspecialchars($article['author_name']??'No disponible') ?></dd></div><div><dt>Actualizado</dt><dd><?= htmlspecialchars(date('d/m/Y H:i',strtotime($article['updated_at']))) ?></dd></div><div><dt>Publicado</dt><dd><?= !empty($article['published_at'])?htmlspecialchars(date('d/m/Y H:i',strtotime($article['published_at']))):'Aún no publicado' ?></dd></div></dl><?php if($problems): ?><div class="knowledge-related"><span class="ticket-kicker">Problemas relacionados</span><?php foreach($problems as $p): ?><a href="<?= APP_BASE_URL ?>/problems/view?id=<?= (int)$p['id'] ?>"><strong><?= htmlspecialchars($p['problem_number']) ?></strong><small><?= htmlspecialchars($p['title']) ?><?= $p['is_primary']?' · Principal':'' ?></small></a><?php endforeach; ?></div><?php endif; ?></div></aside></div>
</div>
<?php require APP_ROOT.'/app/Views/shared/app_end.php'; ?>
